### ISSUE TITLE
BuglySymbolUploadTool error

### ISSUE THREAD

**Issue by zhangfurun** [nevermore-imba/BuglySymbolUploadTool#1]
The operation couldn’t be completed. Permission denied

**Comment by nevermore-imba** [comment]
Can you give me more details ?

**Comment by nevermore-imba** [comment]
@zhangfurun Can you give me more details ?

**Comment by zhangfurun** [comment]
sorry, error in my project......but, run your project, i have other error......

in My Mac, java use 1.8, java info :
```
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
```

input some information, uplpad dsym button, error:
错误: 尝试打开文件buglyqq-upload-symbol.jar时出现意外错误
Task failed

so, i need ?

**Comment by zhangfurun** [comment]
use terminal, input infomation to upload , success

so, how to fix error in your project

**Comment by zhangfurun** [comment]
connect qq 122674287, to easy talk

**Comment by zhangfurun** [comment]
fix finish, error because of my java path, local use jenv manager versions, so path is not /usr/bin/java
